import { Geist, Geist_Mono } from "next/font/google";
import React from "react";

import { APP_DESCRIPTION, APP_NAME, APP_VERSION } from "@/constants/app";
import a from "@/constants/test";
import c from "@/constants/test";

import type { Metadata } from "next";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <h1>
          {APP_NAME} - {APP_VERSION} - {APP_DESCRIPTION} - {a} - {c}
        </h1>
        {children}
      </body>
    </html>
  );
}
